sudo: required
dist: trusty
language: python
cache: pip
python:
    - "3.6-dev"
    - "nightly"

before_install:
    - "echo TRAVIS_PYTHON_VERSION= $TRAVIS_PYTHON_VERSION"
    - python -c 'import sys; print(sys.version)'

install:
    - pip install -U pytest requests pytest-faulthandler
    - pip install -e .

script:
    - py.test -v
